theme: jekyll-theme-cayman
title: "KOALA: A Kalman Optimization Algorithm with Loss Adaptivity"
description: "Aram Davtyan, Sepehr Sameni, Llukman Cerkezi, Givi Meishvili, Adam Bielski, Paolo Favaro. In AAAI, 2022."
